# Generated by Django 5.2 on 2025-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
